### ISSUE TITLE
Non-Interactive Mode

### ISSUE THREAD

**Issue by jUnion44** [UMD-ACES/MITM#12]
**Describe the bug**
When I run a command in non-interactive mode with auto access enabled, I get an error that looks likes this.
![image](https://user-images.githubusercontent.com/24414504/167424813-1f5316f2-c36f-41a4-b2c7-36006436674d.png)

I tried this command, among others
![image](https://user-images.githubusercontent.com/24414504/167424999-34602944-8bcb-4b99-b1d5-7435969cde13.png)

This was on a brand new ubuntu focal lxc container with openssh installed.

**To Reproduce**
1. Make container and install ssh
2. Run mitm server on it
3. Connect using auto access to run a command in non-interactive mode

In addition, banner files do not appear to be displayed on the login prompt.

**Comment by zxlin** [comment]
Non-interactive mode fixed in af78ca52d4ed2ec02b2a7424f26ee7f7e07feb3e
